hyperparameters = {
    "energy": {
        "lightgbm": {
            "learning_rate": {
                0.025: 0.04250556821327426,
                0.25: 0.04664899042727555,
                0.5: 0.03059521040181973,
                0.75: 0.011820784620423637,
                0.975: 0.08540531939716978,
            },
            "n_estimators": {0.025: 804, 0.25: 793, 0.5: 913, 0.75: 967, 0.975: 305},
            "num_leaves": {0.025: 107, 0.25: 137, 0.5: 152, 0.75: 99, 0.975: 113},
            "reg_alpha": {
                0.025: 0.5044005472296809,
                0.25: 0.7312118285798104,
                0.5: 0.7010600914073861,
                0.75: 0.8989049683603231,
                0.975: 0.2490114682169691,
            },
            "features": {
                0.025: [
                    "temperature_2m",
                    "apparent_temperature",
                    "rain",
                    "pressure_msl",
                    "surface_pressure",
                    "cloud_cover_low",
                    "cloud_cover_mid",
                    "vapour_pressure_deficit",
                    "wind_speed_100m",
                    "wind_gusts_10m",
                    "sunshine_duration",
                    "direct_radiation",
                    "direct_normal_irradiance",
                    "shortwave_radiation_instant",
                    "month",
                    "day",
                    "lag_1",
                    "lag_2",
                    "lag_3",
                    "lag_5",
                    "lag_20",
                    "lag_28",
                    "diff_lag_1",
                    "diff_lag_2",
                    "diff_lag_3",
                    "rolling_mean_7",
                    "diff_prev_day",
                    "hour",
                ],
                0.25: [
                    "temperature_2m",
                    "apparent_temperature",
                    "precipitation",
                    "snowfall",
                    "pressure_msl",
                    "cloud_cover_mid",
                    "cloud_cover_high",
                    "vapour_pressure_deficit",
                    "wind_speed_10m",
                    "wind_direction_10m",
                    "wind_direction_100m",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "direct_radiation",
                    "diffuse_radiation",
                    "global_tilted_irradiance",
                    "direct_radiation_instant",
                    "diffuse_radiation_instant",
                    "global_tilted_irradiance_instant",
                    "day",
                    "lag_2",
                    "lag_5",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_4",
                    "is_holiday",
                    "rolling_mean_7",
                    "rolling_std_7",
                    "rolling_std_30",
                    "year",
                    "hour",
                ],
                0.5: [
                    "temperature_2m",
                    "apparent_temperature",
                    "precipitation",
                    "pressure_msl",
                    "surface_pressure",
                    "cloud_cover",
                    "cloud_cover_low",
                    "et0_fao_evapotranspiration",
                    "wind_speed_100m",
                    "wind_direction_10m",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "shortwave_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "global_tilted_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "lag_3",
                    "lag_6",
                    "lag_28",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_2",
                    "diff_lag_3",
                    "diff_lag_4",
                    "is_holiday",
                    "corona_phase",
                    "rolling_mean_7",
                    "year",
                    "hour",
                ],
                0.75: [
                    "temperature_2m",
                    "relative_humidity_2m",
                    "precipitation",
                    "rain",
                    "snowfall",
                    "surface_pressure",
                    "cloud_cover_high",
                    "et0_fao_evapotranspiration",
                    "wind_speed_10m",
                    "wet_bulb_temperature_2m",
                    "direct_radiation",
                    "diffuse_radiation",
                    "direct_normal_irradiance",
                    "shortwave_radiation_instant",
                    "direct_radiation_instant",
                    "diffuse_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "global_tilted_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "day",
                    "quarter",
                    "weekday",
                    "lag_1",
                    "lag_4",
                    "lag_5",
                    "lag_6",
                    "lag_20",
                    "diff_lag_1",
                    "diff_lag_3",
                    "corona_phase",
                    "rolling_mean_7",
                    "rolling_mean_30",
                    "rolling_std_7",
                    "rolling_std_30",
                    "year",
                ],
                0.975: [
                    "temperature_2m",
                    "dew_point_2m",
                    "rain",
                    "snowfall",
                    "cloud_cover",
                    "cloud_cover_low",
                    "cloud_cover_high",
                    "vapour_pressure_deficit",
                    "wind_speed_10m",
                    "wind_speed_100m",
                    "diffuse_radiation",
                    "direct_normal_irradiance",
                    "diffuse_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "global_tilted_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "day",
                    "weekday",
                    "lag_3",
                    "lag_4",
                    "diff_lag_1",
                    "diff_lag_2",
                    "diff_lag_3",
                    "corona_phase",
                    "rolling_mean_7",
                    "rolling_std_7",
                    "rolling_std_30",
                ],
            },
        },
        "mstl": {
            "season_length_one": {
                0.025: 24,
                0.25: 24,
                0.5: 24,
                0.75: 24,
                0.975: 24,
            },
            "season_length_two": {
                0.025: 8760,
                0.25: 8760,
                0.5: 8760,
                0.75: 8760,
                0.975: 8760,
            },
            "historical_length": {
                0.025: 700,
                0.25: 700,
                0.5: 700,
                0.75: 700,
                0.975: 700,
            },
        },
        "linearquantileregression": {
            "fit_intercept": {
                0.025: 1,
                0.25: 1,
                0.5: 1,
                0.75: 1,
                0.975: 1,
            },
            "alpha": {
                0.025: 0.030467806505321222,
                0.25: 0.030503613912711346,
                0.5: 0.0012294978647639572,
                0.75: 0.04261528087591151,
                0.975: 0.019351160680631516,
            },
            "features": {
                0.025: [
                    "dew_point_2m",
                    "apparent_temperature",
                    "rain",
                    "surface_pressure",
                    "cloud_cover_low",
                    "cloud_cover_mid",
                    "vapour_pressure_deficit",
                    "wind_speed_10m",
                    "wind_direction_100m",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "direct_normal_irradiance",
                    "terrestrial_radiation",
                    "shortwave_radiation_instant",
                    "direct_radiation_instant",
                    "diffuse_radiation_instant",
                    "terrestrial_radiation_instant",
                    "day",
                    "lag_1",
                    "lag_6",
                    "lag_7",
                    "lag_14",
                    "lag_28",
                    "diff_lag_3",
                    "corona_phase",
                    "rolling_mean_7",
                    "rolling_mean_30",
                    "rolling_std_30",
                    "diff_prev_day",
                    "hour",
                ],
                0.25: [
                    "temperature_2m",
                    "relative_humidity_2m",
                    "dew_point_2m",
                    "apparent_temperature",
                    "rain",
                    "cloud_cover",
                    "cloud_cover_low",
                    "wind_speed_100m",
                    "wind_direction_10m",
                    "wind_direction_100m",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "diffuse_radiation",
                    "direct_normal_irradiance",
                    "shortwave_radiation_instant",
                    "diffuse_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "day",
                    "quarter",
                    "lag_3",
                    "lag_7",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_4",
                    "rolling_mean_7",
                    "rolling_mean_30",
                    "rolling_std_30",
                    "diff_prev_day",
                    "hour",
                ],
                0.5: [
                    "pressure_msl",
                    "cloud_cover_low",
                    "cloud_cover_mid",
                    "cloud_cover_high",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "shortwave_radiation",
                    "terrestrial_radiation",
                    "direct_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "global_tilted_irradiance_instant",
                    "day",
                    "weekday",
                    "lag_4",
                    "lag_5",
                    "lag_6",
                    "lag_14",
                    "lag_50",
                    "diff_lag_2",
                    "diff_lag_3",
                    "diff_lag_4",
                    "is_holiday",
                    "rolling_mean_7",
                    "rolling_std_30",
                    "diff_prev_day",
                    "year",
                ],
                0.75: [
                    "relative_humidity_2m",
                    "dew_point_2m",
                    "precipitation",
                    "rain",
                    "cloud_cover_low",
                    "cloud_cover_mid",
                    "wind_speed_10m",
                    "wind_speed_100m",
                    "wind_direction_10m",
                    "wind_direction_100m",
                    "wind_gusts_10m",
                    "shortwave_radiation",
                    "direct_radiation",
                    "diffuse_radiation",
                    "direct_normal_irradiance",
                    "shortwave_radiation_instant",
                    "diffuse_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "month",
                    "lag_1",
                    "lag_2",
                    "lag_3",
                    "lag_4",
                    "lag_5",
                    "lag_7",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_3",
                    "diff_lag_4",
                    "is_holiday",
                    "rolling_mean_7",
                    "rolling_mean_30",
                    "hour",
                ],
                0.975: [
                    "temperature_2m",
                    "dew_point_2m",
                    "apparent_temperature",
                    "pressure_msl",
                    "cloud_cover_mid",
                    "cloud_cover_high",
                    "wind_speed_10m",
                    "wind_speed_100m",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "direct_radiation",
                    "shortwave_radiation_instant",
                    "diffuse_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "global_tilted_irradiance_instant",
                    "quarter",
                    "lag_2",
                    "lag_4",
                    "lag_5",
                    "lag_6",
                    "lag_7",
                    "lag_28",
                    "diff_lag_1",
                    "diff_lag_3",
                    "rolling_mean_7",
                    "rolling_mean_30",
                    "rolling_std_30",
                    "diff_prev_day",
                    "year",
                ],
            },
        },
        # "GradientBoostingRegressor": {},
        "Baseline": {},
        "features_for_optuna": [
            "temperature_2m",
            "relative_humidity_2m",
            "dew_point_2m",
            "apparent_temperature",
            "precipitation",
            "rain",
            "snowfall",
            "pressure_msl",
            "surface_pressure",
            "cloud_cover",
            "cloud_cover_low",
            "cloud_cover_mid",
            "cloud_cover_high",
            "et0_fao_evapotranspiration",
            "vapour_pressure_deficit",
            "wind_speed_10m",
            "wind_speed_100m",
            "wind_direction_10m",
            "wind_direction_100m",
            "wind_gusts_10m",
            "wet_bulb_temperature_2m",
            "sunshine_duration",
            "shortwave_radiation",
            "direct_radiation",
            "diffuse_radiation",
            "direct_normal_irradiance",
            "global_tilted_irradiance",
            "terrestrial_radiation",
            "shortwave_radiation_instant",
            "direct_radiation_instant",
            "diffuse_radiation_instant",
            "direct_normal_irradiance_instant",
            "global_tilted_irradiance_instant",
            "terrestrial_radiation_instant",
            "month",
            "day",
            "quarter",
            "weekday",
            "lag_1",
            "lag_2",
            "lag_3",
            "lag_4",
            "lag_5",
            "lag_6",
            "lag_7",
            "lag_14",
            "lag_20",
            "lag_28",
            "lag_50",
            "diff_lag_1",
            "diff_lag_2",
            "diff_lag_3",
            "diff_lag_4",
            "is_holiday",
            "corona_phase",
            "rolling_mean_7",
            "rolling_mean_30",
            "rolling_std_7",
            "rolling_std_30",
            "diff_prev_day",
            "year",
            "hour",
        ],
    },
    "bike": {
        "lightgbm": {
            "learning_rate": {
                0.025: 0.02312095268631553,
                0.25: 0.004822178948288809,
                0.5: 0.06549896736249831,
                0.75: 0.02641951601547135,
                0.975: 0.06667433494265748,
            },
            "n_estimators": {0.025: 420, 0.25: 822, 0.5: 207, 0.75: 661, 0.975: 454},
            "num_leaves": {0.025: 54, 0.25: 108, 0.5: 231, 0.75: 140, 0.975: 63},
            "reg_alpha": {
                0.025: 0.8216747602143716,
                0.25: 0.9464743842189021,
                0.5: 0.6429180343554328,
                0.75: 0.7099297586752856,
                0.975: 0.8803513552135429,
            },
            "features": {
                0.025: [
                    "dew_point_2m",
                    "apparent_temperature",
                    "rain",
                    "snowfall",
                    "cloud_cover",
                    "cloud_cover_high",
                    "shortwave_radiation",
                    "direct_radiation",
                    "diffuse_radiation",
                    "direct_normal_irradiance",
                    "global_tilted_irradiance",
                    "terrestrial_radiation",
                    "shortwave_radiation_instant",
                    "direct_radiation_instant",
                    "diffuse_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "quarter",
                    "weekday",
                    "lag_2",
                    "lag_3",
                    "lag_5",
                    "lag_6",
                    "lag_20",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_3",
                    "diff_lag_4",
                    "is_holiday",
                    "rolling_mean_7",
                    "diff_prev_day",
                    "year",
                ],
                0.25: [
                    "temperature_2m",
                    "precipitation",
                    "snowfall",
                    "cloud_cover",
                    "cloud_cover_low",
                    "cloud_cover_high",
                    "et0_fao_evapotranspiration",
                    "wind_speed_10m",
                    "wind_direction_10m",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "shortwave_radiation",
                    "diffuse_radiation",
                    "global_tilted_irradiance",
                    "direct_radiation_instant",
                    "diffuse_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "global_tilted_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "quarter",
                    "weekday",
                    "lag_1",
                    "lag_2",
                    "lag_3",
                    "lag_6",
                    "lag_7",
                    "lag_20",
                    "diff_lag_4",
                    "is_holiday",
                    "corona_phase",
                    "rolling_mean_7",
                    "rolling_mean_30",
                    "rolling_std_30",
                    "year",
                ],
                0.5: [
                    "temperature_2m",
                    "apparent_temperature",
                    "precipitation",
                    "pressure_msl",
                    "cloud_cover_mid",
                    "et0_fao_evapotranspiration",
                    "wind_speed_100m",
                    "wind_direction_100m",
                    "shortwave_radiation",
                    "direct_normal_irradiance",
                    "diffuse_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "month",
                    "weekday",
                    "lag_1",
                    "lag_3",
                    "lag_4",
                    "lag_5",
                    "lag_7",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_3",
                    "is_holiday",
                    "rolling_mean_7",
                    "rolling_mean_30",
                    "diff_prev_day",
                ],
                0.75: [
                    "temperature_2m",
                    "precipitation",
                    "snowfall",
                    "pressure_msl",
                    "cloud_cover",
                    "cloud_cover_high",
                    "vapour_pressure_deficit",
                    "wind_speed_10m",
                    "wind_speed_100m",
                    "wind_direction_100m",
                    "wind_gusts_10m",
                    "sunshine_duration",
                    "direct_radiation",
                    "global_tilted_irradiance",
                    "terrestrial_radiation",
                    "global_tilted_irradiance_instant",
                    "day",
                    "weekday",
                    "lag_1",
                    "lag_2",
                    "lag_3",
                    "lag_4",
                    "lag_5",
                    "lag_6",
                    "lag_7",
                    "lag_14",
                    "lag_20",
                    "lag_50",
                    "is_holiday",
                    "rolling_mean_7",
                    "rolling_std_7",
                    "diff_prev_day",
                ],
                0.975: [
                    "dew_point_2m",
                    "rain",
                    "snowfall",
                    "pressure_msl",
                    "surface_pressure",
                    "cloud_cover_low",
                    "et0_fao_evapotranspiration",
                    "wind_speed_10m",
                    "wind_speed_100m",
                    "wind_direction_10m",
                    "diffuse_radiation",
                    "direct_normal_irradiance",
                    "global_tilted_irradiance",
                    "terrestrial_radiation",
                    "shortwave_radiation_instant",
                    "diffuse_radiation_instant",
                    "terrestrial_radiation_instant",
                    "day",
                    "quarter",
                    "weekday",
                    "lag_4",
                    "lag_6",
                    "lag_28",
                    "diff_lag_2",
                    "is_holiday",
                    "rolling_mean_7",
                    "rolling_std_7",
                    "diff_prev_day",
                ],
            },
        },
        "mstl": {
            "season_length_one": {0.025: 7, 0.25: 7, 0.5: 7, 0.75: 7, 0.975: 7},
            "season_length_two": {
                0.025: 365,
                0.25: 365,
                0.5: 365,
                0.75: 365,
                0.975: 365,
            },
            "historical_length": {
                0.025: 700,
                0.25: 700,
                0.5: 700,
                0.75: 700,
                0.975: 700,
            },
        },
        "linearquantileregression": {
            "fit_intercept": {
                0.025: 1,
                0.25: 1,
                0.5: 1,
                0.75: 1,
                0.975: 1,
            },
            "alpha": {
                0.025: 0.04383972666524161,
                0.25: 0.004077132028419962,
                0.5: 0.009021460404823699,
                0.75: 0.047943426402482225,
                0.975: 0.0006393250797273389,
            },
            "features": {
                0.025: [
                    "temperature_2m",
                    "dew_point_2m",
                    "apparent_temperature",
                    "precipitation",
                    "rain",
                    "cloud_cover",
                    "cloud_cover_low",
                    "cloud_cover_high",
                    "et0_fao_evapotranspiration",
                    "vapour_pressure_deficit",
                    "wind_speed_10m",
                    "wind_speed_100m",
                    "direct_normal_irradiance",
                    "terrestrial_radiation",
                    "terrestrial_radiation_instant",
                    "month",
                    "lag_3",
                    "lag_4",
                    "lag_5",
                    "lag_6",
                    "lag_7",
                    "lag_14",
                    "lag_28",
                    "diff_lag_2",
                    "diff_lag_3",
                    "rolling_mean_30",
                    "diff_prev_day",
                    "year",
                ],
                0.25: [
                    "apparent_temperature",
                    "rain",
                    "snowfall",
                    "pressure_msl",
                    "cloud_cover_mid",
                    "cloud_cover_high",
                    "et0_fao_evapotranspiration",
                    "vapour_pressure_deficit",
                    "wind_speed_10m",
                    "wind_direction_10m",
                    "wind_direction_100m",
                    "wind_gusts_10m",
                    "sunshine_duration",
                    "diffuse_radiation",
                    "terrestrial_radiation",
                    "direct_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "day",
                    "weekday",
                    "lag_1",
                    "lag_2",
                    "lag_3",
                    "lag_6",
                    "lag_7",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_4",
                    "is_holiday",
                    "rolling_std_7",
                    "year",
                ],
                0.5: [
                    "temperature_2m",
                    "relative_humidity_2m",
                    "dew_point_2m",
                    "apparent_temperature",
                    "snowfall",
                    "surface_pressure",
                    "cloud_cover_mid",
                    "cloud_cover_high",
                    "wind_speed_100m",
                    "wind_direction_100m",
                    "wet_bulb_temperature_2m",
                    "direct_radiation",
                    "diffuse_radiation",
                    "direct_normal_irradiance",
                    "global_tilted_irradiance",
                    "terrestrial_radiation",
                    "direct_normal_irradiance_instant",
                    "global_tilted_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "month",
                    "quarter",
                    "weekday",
                    "lag_3",
                    "lag_5",
                    "lag_7",
                    "lag_14",
                    "lag_20",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_2",
                    "is_holiday",
                    "corona_phase",
                    "rolling_mean_30",
                    "diff_prev_day",
                ],
                0.75: [
                    "dew_point_2m",
                    "pressure_msl",
                    "cloud_cover",
                    "cloud_cover_low",
                    "cloud_cover_high",
                    "vapour_pressure_deficit",
                    "wind_speed_10m",
                    "wind_direction_10m",
                    "wind_direction_100m",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "shortwave_radiation",
                    "terrestrial_radiation",
                    "direct_normal_irradiance_instant",
                    "month",
                    "weekday",
                    "lag_1",
                    "lag_2",
                    "lag_3",
                    "lag_4",
                    "lag_5",
                    "lag_7",
                    "lag_14",
                    "lag_28",
                    "diff_lag_4",
                    "corona_phase",
                    "rolling_std_7",
                    "rolling_std_30",
                ],
                0.975: [
                    "temperature_2m",
                    "dew_point_2m",
                    "apparent_temperature",
                    "snowfall",
                    "pressure_msl",
                    "surface_pressure",
                    "cloud_cover",
                    "cloud_cover_low",
                    "cloud_cover_mid",
                    "et0_fao_evapotranspiration",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "shortwave_radiation",
                    "direct_radiation",
                    "global_tilted_irradiance",
                    "shortwave_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "global_tilted_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "weekday",
                    "lag_1",
                    "lag_2",
                    "lag_5",
                    "lag_20",
                    "lag_28",
                    "diff_lag_1",
                    "is_holiday",
                    "rolling_std_30",
                    "diff_prev_day",
                    "year",
                ],
            },
        },
        "gradientboostingregressor": {
            "learning_rate": {
                0.025: 0.02282364167854684,
                0.25: 0.04093469195464335,
                0.5: 0.0778039148436888,
                0.75: 0.011526225642107299,
                0.975: 0.04708364602781278,
            },
            "n_estimators": {0.025: 831, 0.25: 147, 0.5: 898, 0.75: 853, 0.975: 368},
            "features": {
                0.025: [
                    "relative_humidity_2m",
                    "precipitation",
                    "snowfall",
                    "surface_pressure",
                    "cloud_cover_low",
                    "cloud_cover_mid",
                    "cloud_cover_high",
                    "et0_fao_evapotranspiration",
                    "vapour_pressure_deficit",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "shortwave_radiation",
                    "direct_radiation",
                    "terrestrial_radiation",
                    "lag_4",
                    "lag_7",
                    "lag_20",
                    "lag_50",
                    "is_holiday",
                    "rolling_mean_7",
                    "rolling_std_7",
                    "diff_prev_day",
                ],
                0.25: [
                    "relative_humidity_2m",
                    "dew_point_2m",
                    "apparent_temperature",
                    "precipitation",
                    "surface_pressure",
                    "direct_radiation",
                    "global_tilted_irradiance",
                    "shortwave_radiation_instant",
                    "direct_radiation_instant",
                    "diffuse_radiation_instant",
                    "direct_normal_irradiance_instant",
                    "global_tilted_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "month",
                    "weekday",
                    "lag_1",
                    "lag_4",
                    "lag_5",
                    "lag_6",
                    "lag_7",
                    "lag_28",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_3",
                    "is_holiday",
                    "corona_phase",
                    "rolling_std_7",
                ],
                0.5: [
                    "relative_humidity_2m",
                    "snowfall",
                    "pressure_msl",
                    "surface_pressure",
                    "cloud_cover_low",
                    "cloud_cover_mid",
                    "cloud_cover_high",
                    "vapour_pressure_deficit",
                    "wind_speed_100m",
                    "wind_direction_10m",
                    "wind_direction_100m",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "direct_radiation",
                    "global_tilted_irradiance",
                    "direct_radiation_instant",
                    "diffuse_radiation_instant",
                    "global_tilted_irradiance_instant",
                    "terrestrial_radiation_instant",
                    "quarter",
                    "weekday",
                    "lag_1",
                    "lag_2",
                    "lag_4",
                    "lag_5",
                    "lag_20",
                    "lag_28",
                    "lag_50",
                    "diff_lag_1",
                    "diff_lag_2",
                    "corona_phase",
                    "rolling_std_7",
                    "rolling_std_30",
                    "diff_prev_day",
                ],
                0.75: [
                    "relative_humidity_2m",
                    "cloud_cover",
                    "cloud_cover_high",
                    "wind_speed_100m",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "shortwave_radiation",
                    "direct_normal_irradiance",
                    "global_tilted_irradiance",
                    "terrestrial_radiation",
                    "month",
                    "day",
                    "quarter",
                    "weekday",
                    "lag_1",
                    "lag_3",
                    "lag_4",
                    "lag_5",
                    "lag_6",
                    "lag_7",
                    "lag_20",
                    "lag_28",
                    "diff_lag_2",
                    "is_holiday",
                    "corona_phase",
                    "rolling_mean_30",
                    "rolling_std_7",
                    "rolling_std_30",
                ],
                0.975: [
                    "relative_humidity_2m",
                    "dew_point_2m",
                    "precipitation",
                    "pressure_msl",
                    "cloud_cover",
                    "cloud_cover_mid",
                    "vapour_pressure_deficit",
                    "wind_speed_10m",
                    "wind_speed_100m",
                    "wind_direction_10m",
                    "wind_gusts_10m",
                    "wet_bulb_temperature_2m",
                    "sunshine_duration",
                    "direct_radiation",
                    "direct_normal_irradiance",
                    "global_tilted_irradiance",
                    "shortwave_radiation_instant",
                    "global_tilted_irradiance_instant",
                    "month",
                    "day",
                    "weekday",
                    "lag_1",
                    "lag_2",
                    "lag_3",
                    "lag_6",
                    "lag_7",
                    "lag_20",
                    "diff_lag_1",
                    "rolling_mean_7",
                    "rolling_std_7",
                    "year",
                ],
            },
            "Baseline": {},
        },
        "features_for_optuna": [
            "temperature_2m",
            "relative_humidity_2m",
            "dew_point_2m",
            "apparent_temperature",
            "precipitation",
            "rain",
            "snowfall",
            "pressure_msl",
            "surface_pressure",
            "cloud_cover",
            "cloud_cover_low",
            "cloud_cover_mid",
            "cloud_cover_high",
            "et0_fao_evapotranspiration",
            "vapour_pressure_deficit",
            "wind_speed_10m",
            "wind_speed_100m",
            "wind_direction_10m",
            "wind_direction_100m",
            "wind_gusts_10m",
            "wet_bulb_temperature_2m",
            "sunshine_duration",
            "shortwave_radiation",
            "direct_radiation",
            "diffuse_radiation",
            "direct_normal_irradiance",
            "global_tilted_irradiance",
            "terrestrial_radiation",
            "shortwave_radiation_instant",
            "direct_radiation_instant",
            "diffuse_radiation_instant",
            "direct_normal_irradiance_instant",
            "global_tilted_irradiance_instant",
            "terrestrial_radiation_instant",
            "month",
            "day",
            "quarter",
            "weekday",
            "lag_1",
            "lag_2",
            "lag_3",
            "lag_4",
            "lag_5",
            "lag_6",
            "lag_7",
            "lag_14",
            "lag_20",
            "lag_28",
            "lag_50",
            "diff_lag_1",
            "diff_lag_2",
            "diff_lag_3",
            "diff_lag_4",
            "is_holiday",
            "corona_phase",
            "rolling_mean_7",
            "rolling_mean_30",
            "rolling_std_7",
            "rolling_std_30",
            "diff_prev_day",
            "year",
        ],
    },
}
